apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  # namespace: my-namespace #------Adding pod to particular namespace
  labels:
    app: my-app
    env: dev
spec:
  containers:
    #1st Container
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80

    #2nd Container
    - name: db-container
      image: mariadb
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Redhat

# apiVersion: v1 → Using core Kubernetes API
# kind: Pod → We are creating a Pod
# metadata → Information about the Pod
# name → Pod name
# labels → Used for grouping/selecting pods
# spec → Actual configuration
# containers → List of containers inside Pod
# name → Container name
# image → Docker image (here: nginx)
# ports → Port exposed by container

# kubectl apply -f pod.yaml
# kubectl get pods
