apiVersion: v1
kind: Secret
metadata:
  name: my-sec
type: Opaque
data:
  my_pass: "Q2xvdWRibGl0ekAxMjM=" # base64 for "root"
  my_user: "c2h1YmhhbQ==" # base64 for "Redhat@123"


# kind: Secret → Stores sensitive data
# type: Opaque → Default secret type
# data → Values must be base64 encoded

# 🔹 How to Encode Values
# echo -n "root" | base64
# echo -n "Redhat@123" | base64

# kubectl apply -f secret.yaml
# kubectl get secrets
# kubectl describe secret my-secret

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: my-container
      image: nginx
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-sec
              key: my_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: my-sec
              key: my_pass
