apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
  labels:
    app: sts-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sts-app
    spec:
      containers:
        - name: my-c
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Redhat
  selector:
    matchLabels:
      app: sts-app


# kind: StatefulSet → Used for stateful applications
# serviceName → Required (points to a Headless Service)
# replicas: 3 → Creates 3 Pods

# Pods are created with stable names:
# my-statefulset-0
# my-statefulset-1
# my-statefulset-2

# Each Pod gets:
# Unique identity
# Stable hostname
# Persistent storage (if configured)

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: sts-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: sts-app
